### ISSUE TITLE
BehaviourTree 시퀀스 노드 수정

### ISSUE THREAD

**Issue by password-kim** [KIA-PROGRAMMING-38/2DProject-TeamfightManager#1]

**Comment by minoRiver** [comment]
기존의 셀렉터 및 시퀀스 노드에서 Update() 결과가 Running이여도 다음 노드를 실행했는데 이 부분에 대해서 수정작업을 진행해 Running 상태일 경우 다음 노드를 실행하지 않고 종료되며 다음번에 실행되더라도 Running 상태인 애부터 실행하도록 수정했다.

![시퀀스노드 수정전](https://user-images.githubusercontent.com/120010342/229034604-84ff066f-0afc-49a3-bfbd-5cb3b4b7316a.png)

![시퀀스노드 수정후](https://user-images.githubusercontent.com/120010342/229034607-f8ce6efc-331f-43ea-9db0-9ee6a34ade1b.png)
