### ISSUE TITLE
[Feature] 검사 궁극기 기능 추가

### ISSUE THREAD

**Issue by minoRiver** [KIA-PROGRAMMING-38/2DProject-TeamfightManager#12]
# 설명
현재 구현해 놓은 공격행동 시스템으로 검사 궁극기 기능을 만든다.
검사 궁극기 행동 시 발생하는 이펙트 및 행동에서 해야할 기능들을 구현한다.

궁극기 행동 시 알맞은 궁극기 이펙트를 보여주고 부자연스럽지 않게 행동과 싱크를 맞춰준다.

# 참고자료
아래 그림에서 왼쪽(파랑팀)맨위의 챔피언을 보면 시원하게 베고 가는 동작이 있는데 그 것이 구현해야할 궁극기다.
![검사 궁극기 짤](https://user-images.githubusercontent.com/120010342/230295949-577db7c4-9654-4c8e-9c85-41ab7b343744.gif)

# 주의사항
애니메이션 중간에 실제 해야할 행동들이 실행되기 때문에 애니메이션 이벤트로 받아서 실행해야 하는데 이벤트는 string을 인자로 받기 때문에 오타에 주의해야 한다.

**Comment by minoRiver** [comment]
ㅁㄴㅇㅁㄴㅇ

**Comment by ChoiSeonMun** [comment]
자세하게 설명을 달아주세요 ^^
