### ISSUE TITLE
[Feature] 배틀 스테이지 시스템 구현

### ISSUE THREAD

**Issue by minoRiver** [KIA-PROGRAMMING-38/2DProject-TeamfightManager#13]
# 설명
정해진 시간동안 각팀의 챔피언들끼리 싸우는 시스템이다.

[정리 파일 링크](https://docs.google.com/document/d/1lCQAnNFOA9xJef08u8LMf5jA0CXtWYQm6Lz1cNYRl9I/edit)

# 주의사항
전투 종료 시 챔피언들끼리 싸우는 것을 멈춰야 한다.

**Comment by ChoiSeonMun** [comment]
시스템 기획서 링크 달아주세요
