### ISSUE TITLE
[Feature] 궁극기 이펙트 추가 및 싱크 맞추기

### ISSUE THREAD

**Issue by minoRiver** [KIA-PROGRAMMING-38/2DProject-TeamfightManager#14]
# 설명
궁극기 행동 시 알맞은 궁극기 이펙트를 보여주고 부자연스럽지 않게 행동과 싱크를 맞춰준다.

# 참고자료
![검사 궁극기 짤](https://user-images.githubusercontent.com/120010342/230295949-577db7c4-9654-4c8e-9c85-41ab7b343744.gif)

**Comment by ChoiSeonMun** [comment]
#12 과 통합해서 진행
