### ISSUE TITLE
BehaviourTree 관련 구조 수정

### ISSUE THREAD

**Issue by password-kim** [KIA-PROGRAMMING-38/2DProject-TeamfightManager#2]

**Comment by minoRiver** [comment]
BehaviourTree 관련 구조를 수정했다.

BehaviourTree와 AIController, Blackboard 는 원래 MonoBehaviour를 상속받아 사용했는데 이벤트 함수 호출 순서로 인해 꼬여버리는 일이 발생하게 되면서(Blackboard의 Awake에서는 Container들을 Clear하는 작업을 하고 BehaviourTree의 OnDisable에서는 Blackboard에 값을 저장 혹은 갱신하는 작업을 함) 구조를 전체적으로 수정하려고 한다.

AIController에서 BehaviourTree를 생성하고 BehaviourTree에서 Blackboard를 생성하는 구조로 변경하고 BehaviourTree와 Blackboard는 나중에 ScriptableObject를 상속받을 수도 있어서 일단은 아무것도 상속받지 않은 상태로 변경해놨다.

사실 Blackboard의 Awake에서 Clear()를 시킬 필요는 없어서 그냥 함수를 빼면 그만이지만 혹시 모를 일을 대비해 구조를 바꾸는 이유가 큰 것 같다.

![image](https://user-images.githubusercontent.com/120010342/229060920-ec024d93-ae87-4da4-8b8b-c466ffa63f58.png)

![image](https://user-images.githubusercontent.com/120010342/229060994-d1f2d636-40d1-474b-8ea7-af9f7472edca.png)

<br></br>
일단 바꾸고 난 후의 구조인데 이 것은 만약 ScriptableObject를 공부하고 적용한다면 한 번 더 바꿔야 할 듯 하다. 지금 당장은 일단 함수 호출 순서로 인해 꼬일 일은 없기 때문에 당장은 이대로 쓸 것 같다.
![image](https://user-images.githubusercontent.com/120010342/229061443-b3c7f7da-fb34-4b79-bad4-6106e0b5f23a.png)
![image](https://user-images.githubusercontent.com/120010342/229062055-06ea51ec-ce0a-4e38-a6bf-f8d5669e434c.png)
![image](https://user-images.githubusercontent.com/120010342/229061938-d6ee1141-69e2-4cd2-a6d9-c4e3ddec1ddb.png)

<br></br>
그리고 이왕 수정하는 김에 AI의 Node들이 AIController 를 들고 있었는데 얘보다는 BehaviourTree를 들고 있는게 맞는 것 같아서 이 부분도 수정했다. 이거로 인해서 에러가 참조 관련해서 에러가 발생해 전체적으로 수정했다.

![image](https://user-images.githubusercontent.com/120010342/229063067-e099b1f0-c628-4b08-8524-43d4cb6d40e2.png)

![image](https://user-images.githubusercontent.com/120010342/229062991-0f36e14b-261c-49cf-a7be-90a420558067.png)
