### ISSUE TITLE
[Feature] 배틀 정보 데이터 테이블에 저장 및 event 로직

### ISSUE THREAD

**Issue by minoRiver** [KIA-PROGRAMMING-38/2DProject-TeamfightManager#20]
# 설명
- 배틀 시스템 데이터 테이블에 필요한 정보들을 담고 정보가 갱신될 때마다 event를 실행해 필요한 곳에서 데이터가 갱신될 때마다 바꿔주도록 한다.
- 챔피언에서 공격, Hit 등 다른 챔피언의 데이터를 변경시키는 행동을 할 때마다 데이터 테이블에 전투 정보를 갱신할 수 있도록 한다.

**Comment by ChoiSeonMun** [comment]
전투 시스템
    - 팀
        - 킬
        - 파일럿 이름
        - 아이콘
        - 덱
            - KDA
            - 적에게 가한 피해량
            - 적에게 당한 피해량
            - 힐량
    - 남은 시간

Dictionary 사용할 곳이 안 보임. List로 재설계할 것
